---
swagger: "2.0"
info:
  version: "1.0"
  title: "serverless-poc"
basePath: "/Dev"
schemes:
- "https"
paths:
  /orders:
    get:
      responses: {}
      x-amazon-apigateway-integration:
        credentials: 
          Fn::GetAtt: [ ApiGwExecutionRole, Arn ]
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          # Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetOrders.Arn}/invocations
        passthroughBehavior: "when_no_match"
